name: Create Azure Resources
on:
  push:
    paths:
      - "Infrastructure/**"
      - ".github/workflows/infrastructure.yml"
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: demo-gh-actions-helloworld

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          region: westeurope
          template: repo/Infrastructure/webapp.bicep
          parameters: repo/Infrastructure/webapp.parameters.json webAppName=${{env.AZURE_WEBAPP_NAME}}
